#!/bin/bash
# shellcheck disable=SC2034

# pictl cli standard theme

set -eo pipefail

THEME_DETAIL="GREY"
THEME_ENTITY="LIGHT_BLUE"
THEME_HEADER="CYAN"
THEME_HIGHLIGHT="LIGHT_RED"
THEME_INFO="WHITE"
THEME_QUOTES="GREY"
THEME_TITLE="LIGHT_GREEN"

THEME_BRACKETS_STYLE_1="WHITE"
THEME_BRACKETS_STYLE_1_INNER="GREY"

THEME_BRACKETS_STYLE_2="GREY"
THEME_BRACKETS_STYLE_2_INNER="GREY"

THEME_DEVICE="LIGHT_BLUE"
THEME_DEVICE_CONNECTORS="GREY"

THEME_DISK_GAUGE_SPACE_CRITICAL="RED"
THEME_DISK_GAUGE_SPACE_WARNING="YELLOW"
THEME_DISK_GAUGE_SPACE_OK="GREEN"

THEME_DISK_INDICATOR_SPACE_FREE="GREY"
THEME_DISK_INDICATOR_ACTIVE="YELLOW"
THEME_DISK_INDICATOR_IDLE="GREY"

THEME_LOGGER_ERROR="RED"
THEME_LOGGER_INFO="WHITE"
THEME_LOGGER_NOTICE="GREY"
THEME_LOGGER_SUCCESS="GREEN"
THEME_LOGGER_WARNING="YELLOW"
