#!/bin/bash
# shellcheck disable=SC2034

# pictl cli standard theme

set -eo pipefail

THEME_DETAIL="${COLOUR_GRAY}"
THEME_ENTITY="${COLOUR_LIGHT_BLUE}"
THEME_HEADER="${COLOUR_CYAN}"
THEME_HIGHLIGHT="${COLOUR_LIGHT_RED}"
THEME_INFO="${COLOUR_WHITE}"
THEME_QUOTES="${COLOUR_GRAY}"
THEME_TITLE="${COLOUR_LIGHT_GREEN}"

THEME_BRACKETS_STYLE_1="${COLOUR_WHITE}"
THEME_BRACKETS_STYLE_1_INNER="${COLOUR_GRAY}"

THEME_BRACKETS_STYLE_2="${COLOUR_GRAY}"
THEME_BRACKETS_STYLE_2_INNER="${COLOUR_GRAY}"

THEME_DEVICE="${THEME_ENTITY}"
THEME_DEVICE_CONNECTORS="${COLOUR_GRAY}"

THEME_DISK_GAUGE_SPACE_CRITICAL="${COLOUR_RED}"
THEME_DISK_GAUGE_SPACE_WARNING="${COLOUR_YELLOW}"
THEME_DISK_GAUGE_SPACE_OK="${COLOUR_GREEN}"

THEME_DISK_INDICATOR_SPACE_FREE="${COLOUR_GRAY}"
THEME_DISK_INDICATOR_ACTIVE="${COLOUR_YELLOW}"
THEME_DISK_INDICATOR_IDLE="${COLOUR_GRAY}"

THEME_LOGGER_ERROR="${COLOUR_RED}"
THEME_LOGGER_INFO="${COLOUR_WHITE}"
THEME_LOGGER_NOTICE="${COLOUR_GRAY}"
THEME_LOGGER_SUCCESS="${COLOUR_GREEN}"
THEME_LOGGER_WARNING="${COLOUR_YELLOW}"
