#!/bin/bash

teardown() {
  unset RPI_BACKUP_JOB_NAME
  unset RPI_BACKUP_JOB_GROUP
  unset RPI_BACKUP_JOB_LOCAL_SOURCE
  unset RPI_BACKUP_JOB_LOCAL_RSYNC_FOLDER
  unset RPI_BACKUP_JOB_LOCAL_TARBALL_FOLDER
  unset RPI_BACKUP_JOB_LOCAL_TARBALL_VERSIONS
  unset RPI_BACKUP_JOB_REMOTE_ENCRYPTION_KEY_PATH
  unset RPI_BACKUP_JOB_REMOTE_TARGET
  unset RPI_BACKUP_JOB_REMOTE_PARAMETER
}

_fixture_set_variable_content() {
  local variable_name
  local variable_names=()

  stdlib.array.make.from_string variable_names "|" "${TEST_VARIABLE_NAMES_DEFINITION}"

  for variable_name in "${variable_names[@]}"; do
    printf -v "RPI_BACKUP_JOB_${variable_name}" "%s" "${variable_name}"
  done
}

@parametrize_with_valid_arguments() {
  # $1: the test function to parametrize

  @parametrize \
    "${1}" \
    "TEST_VARIABLE_NAMES_DEFINITION" \
    "everything_defined____________________;NAME|GROUP|LOCAL_SOURCE|LOCAL_SOURCE_PERMISSION|LOCAL_RSYNC_FOLDER|LOCAL_RSYNC_FOLDER_PERMISSION|LOCAL_TARBALL_FOLDER|LOCAL_TARBALL_FOLDER_PERMISSION|LOCAL_TARBALL_VERSIONS|REMOTE_ENCRYPTION_KEY_PATH|REMOTE_TARGET|REMOTE_PARAMETER"
}

@parametrize_with_invalid_arguments() {
  # $1: the test function to parametrize

  @parametrize \
    "${1}" \
    "TEST_VARIABLE_NAMES_DEFINITION" \
    "name_is_undefined_____________________;GROUP|LOCAL_SOURCE|LOCAL_SOURCE_PERMISSION|LOCAL_RSYNC_FOLDER|LOCAL_RSYNC_FOLDER_PERMISSION|LOCAL_TARBALL_FOLDER|LOCAL_TARBALL_FOLDER_PERMISSION|LOCAL_TARBALL_VERSIONS|REMOTE_ENCRYPTION_KEY_PATH|REMOTE_TARGET|REMOTE_PARAMETER" \
    "group_is_undefined____________________;NAME|LOCAL_SOURCE|LOCAL_SOURCE_PERMISSION|LOCAL_RSYNC_FOLDER_PERMISSION|LOCAL_RSYNC_FOLDER|LOCAL_TARBALL_FOLDER|LOCAL_TARBALL_FOLDER_PERMISSION|LOCAL_TARBALL_VERSIONS|REMOTE_ENCRYPTION_KEY_PATH|REMOTE_TARGET|REMOTE_PARAMETER" \
    "no_task_defined_______________________;NAME|GROUP|LOCAL_RSYNC_FOLDER|LOCAL_RSYNC_FOLDER_PERMISSION|LOCAL_TARBALL_FOLDER|LOCAL_TARBALL_FOLDER_PERMISSION|LOCAL_TARBALL_VERSIONS|REMOTE_ENCRYPTION_KEY_PATH|REMOTE_TARGET|REMOTE_PARAMETER" \
    "source_is_undefined___________________;NAME|GROUP|LOCAL_RSYNC_FOLDER|LOCAL_RSYNC_FOLDER_PERMISSION|LOCAL_TARBALL_FOLDER|LOCAL_TARBALL_FOLDER_PERMISSION|LOCAL_TARBALL_VERSIONS|REMOTE_ENCRYPTION_KEY_PATH|REMOTE_TARGET|REMOTE_PARAMETER" \
    "tarball_without_version_count_________;NAME|GROUP|LOCAL_SOURCE|LOCAL_SOURCE_PERMISSION|LOCAL_RSYNC_FOLDER|LOCAL_RSYNC_FOLDER_PERMISSION|LOCAL_TARBALL_FOLDER|LOCAL_TARBALL_FOLDER_PERMISSION|REMOTE_ENCRYPTION_KEY_PATH|REMOTE_TARGET|REMOTE_PARAMETER" \
    "version_count_without_tarball_________;NAME|GROUP|LOCAL_SOURCE|LOCAL_SOURCE_PERMISSION|LOCAL_RSYNC_FOLDER|LOCAL_RSYNC_FOLDER_PERMISSION|LOCAL_TARBALL_FOLDER|LOCAL_TARBALL_FOLDER_PERMISSION|REMOTE_ENCRYPTION_KEY_PATH|REMOTE_TARGET|REMOTE_PARAMETER" \
    "remote_parameter_without_remote_target;NAME|GROUP|LOCAL_SOURCE|LOCAL_SOURCE_PERMISSION|LOCAL_RSYNC_FOLDER|LOCAL_RSYNC_FOLDER_PERMISSION|LOCAL_TARBALL_FOLDER|LOCAL_TARBALL_FOLDER_PERMISSION|LOCAL_TARBALL_VERSIONS|REMOTE_PARAMETER" \
    "encryption_key_without_remote_target__;NAME|GROUP|LOCAL_SOURCE|LOCAL_SOURCE_PERMISSION|LOCAL_RSYNC_FOLDER|LOCAL_RSYNC_FOLDER_PERMISSION|LOCAL_TARBALL_FOLDER|LOCAL_TARBALL_FOLDER_PERMISSION|LOCAL_TARBALL_VERSIONS|REMOTE_ENCRYPTION_KEY_PATH"
}

test_backup_job_validation__@vary__returns_status_code_1() {
  _fixture_set_variable_content

  _capture.rc _backup_job_validation_argument_combinations

  assert_rc 1
}

@parametrize_with_invalid_arguments \
  test_backup_job_validation__@vary__returns_status_code_1

test_backup_job_validation__@vary__returns_status_code_0() {
  _fixture_set_variable_content

  _capture.rc _backup_job_validation_argument_combinations

  assert_rc 0
}

@parametrize_with_valid_arguments \
  test_backup_job_validation__@vary__returns_status_code_0
