---
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args:
          - "-c"
          - "./.yamllint.yml"
        stages: [pre-commit]
  - repo: https://github.com/cicd-tools-org/pre-commit.git
    rev: 0.6.0
    hooks:
      - id: format-shell
        args:
          - "-w"
          - "--indent=2"
          - "-ci"
          - "-sr"
        files: "^.+\\.(bash|sh)$|^pictl"
      - id: format-toml
      - id: git-conflict-markers
        exclude: "^stdlib/logger/tests/test_stdlib_logger_traceback.sh$"
      - id: lint-github-workflow
      - id: lint-github-workflow-header
      - id: lint-markdown
        args:
          - "-c"
          - ".markdownlint.yml"
      - id: lint-shell
        args:
          - "--color=always"
          - "--source-path=SCRIPTDIR"
          - "--exclude=SC2317"
          - "-x"
      - id: pre-commit-sort-config
      - id: security-credentials
      - id: spelling-commit-message
      - id: spelling-markdown
      - id: spelling-vale-sync
      - id: spelling-vale-vocab
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.2.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-jsonschema
        name: check-github-workflow-push-schema
        files: "^\\.github/config/workflows/workflow-push.json$"
        args:
          - "--schemafile"
          - ".github/config/schemas/workflows/workflow-push.json"
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: bash-coverage-stdlib
        name: ensure the stdlib folder meets coverage requirements
        entry: bash -c 'TEST_CONTAINER_CI=1 ./testing/container.sh collect_coverage stdlib'
        language: system
        stages: [manual]
        pass_filenames: false
        require_serial: true
      - id: headers-source-file-library-root
        name: ensure lib root has correct header
        entry: "\\A(?!#!/bin/bash\n(# shellcheck disable=.+\n){0,1}\nset -Eeo pipefail\n).+\\Z"
        args: [--multiline]
        language: pygrep
        files: "^(lib/__all__.sh)$"
      - id: headers-source-file-module-roots
        name: ensure lib module roots have correct headers
        entry: "\\A(?!#!/bin/bash\n(# shellcheck disable=.+\n){0,1}\nset -eo pipefail\n).+\\Z"
        args: [--multiline]
        language: pygrep
        files: "^(.+/__all__.sh)$"
        exclude: "^(lib/__all__.sh)$"
      - id: headers-source-files
        name: ensure lib source files have correct headers
        entry: "\\A(?!#!/bin/bash\n(# shellcheck disable=.+\n){0,1}\n# pictl.+\nset -eo pipefail\n).+\\Z"
        args: [--multiline]
        language: pygrep
        files: "^lib/.+\\.sh$"
        exclude: "^(.+tests/.+\\.sh|.+/__all__.sh|lib/defaults.sh)$"
      - id: headers-stdlib-source-files
        name: ensure stdlib source files have correct headers
        entry: "\\A(?!#!/bin/bash\n(# shellcheck disable=.+\n){0,1}\n# stdlib.+\nbuiltin set -eo pipefail\n).+\\Z"
        args: [--multiline]
        language: pygrep
        files: "^stdlib/.+\\.sh$"
        exclude: "^(.+tests/.+\\.sh|stdlib/trap/trap.sh)$"
      - id: headers-stdlib-source-files-exporting-traps
        name: ensure stdlib source files exporting traps have correct headers
        entry: "\\A(?!#!/bin/bash\n(# shellcheck disable=.+\n){0,1}\n# stdlib.+\nbuiltin set -Eeo pipefail\n).+\\Z"
        args: [--multiline]
        language: pygrep
        files: "^stdlib/trap/trap.sh$"
      - id: headers-test-files
        name: ensure test files have correct headers
        entry: "\\A(?!#!/bin/bash\n).+\\Z"
        args: [--multiline]
        language: pygrep
        files: "^(.+tests/.*/test_.+\\.sh)$"
      - id: source-test-files
        name: ensure test files do not use the source keyword for imports
        entry: "\\A#!/bin/bash\n.+((^ *|^ +|; *|\\| *|\\& *)(source |\\. )(\".+?\"|\\S+) *(;*)$)+.+\\Z"
        args: [--multiline]
        language: pygrep
        files: "^(.+tests/.*/test_.+\\.sh)$"
      - id: stdlib-builtins-source-files
        name: ensure stdlib source files use builtins prefaced with the 'builtin' command
        entry: "^(?!\\s*#).*(?<!builtin )(?!.*# noqa)(?<!\\S)(break|continue|command|declare|echo|eval|false|printf|true|unset) .*$"
        args: [--multiline]
        language: pygrep
        files: "^stdlib/.+\\.sh$"
        exclude: "^(.+tests/.+\\.sh)$"
