#!/bin/bash

set -eo pipefail

if [[ -n "${RPI_DEBUG}" ]]; then
  trap error_handler ERR
fi

RPI_HOSTNAME="$(hostname)"
RPI_WORKING_DIRECTORY="$(realpath "$(dirname "$0")")"

# Global Environment Variable Defaults
export RPI_PATH_BACKUP="${RPI_PATH_BACKUP}"
export RPI_RESTART_POLICY="${RPI_RESTART_POLICY:-no}"
export RPI_ROOT="${RPI_ROOT:-/mnt/media}"

# Plex Environment Variable Defaults
export RPI_PLEX_PATH_CONFIG="${RPI_PLEX_PATH_CONFIG:-${RPI_ROOT}/plex/config}"
export RPI_PLEX_PATH_TRANSCODE="${RPI_PLEX_PATH_TRANSCODE:-${RPI_ROOT}/plex/transcode}"

# Samba Environment Variable Defaults
export RPI_SAMBA_CREDENTIALS_PASSWORD="${RPI_SAMBA_CREDENTIALS_PASSWORD}"
export RPI_SAMBA_CREDENTIALS_USERNAME="${RPI_SAMBA_CREDENTIALS_USERNAME}"
export RPI_SAMBA_HOSTNAME="${RPI_SAMBA_HOSTNAME:-${RPI_HOSTNAME}}"
export RPI_SAMBA_PATH_CONFIG="${RPI_SAMBA_PATH_CONFIG:-${RPI_ROOT}/samba}"
export RPI_SAMBA_SERVICE_DISCOVERY="${RPI_SAMBA_SERVICE_DISCOVERY:-1}"
export RPI_SAMBA_SUBNET="${RPI_SAMBA_SUBNET}"
export RPI_SAMBA_WORKGROUP="${RPI_SAMBA_WORKGROUP:-"WORKGROUP"}"

# Syncthing Environment Variable Defaults
export RPI_SYNCTHING_CREDENTIALS_PASSWORD="${RPI_SYNCTHING_CREDENTIALS_PASSWORD}"
export RPI_SYNCTHING_CREDENTIALS_USERNAME"${RPI_SYNCTHING_CREDENTIALS_USERNAME}"
export RPI_SYNCTHING_PATH_CONFIG="${RPI_SYNCTHING_PATH_CONFIG:-${RPI_ROOT}/syncthing}"

# Service Selection Defaults
RPI_SERVICES=("${RPI_SERVICES[@]:-plex}" "${RPI_SERVICES[@]:-samba}")

# shellcheck source=lib/configuration.sh
source "${RPI_WORKING_DIRECTORY}/lib/configuration.sh"
# shellcheck source=lib/debug.sh
source "${RPI_WORKING_DIRECTORY}/lib/debug.sh"
# shellcheck source=lib/disk.sh
source "${RPI_WORKING_DIRECTORY}/lib/disk.sh"
# shellcheck source=lib/docker.sh
source "${RPI_WORKING_DIRECTORY}/lib/docker.sh"
# shellcheck source=lib/event.sh
source "${RPI_WORKING_DIRECTORY}/lib/event.sh"
# shellcheck source=lib/filesystem.sh
source "${RPI_WORKING_DIRECTORY}/lib/filesystem.sh"
# shellcheck source=lib/io.sh
source "${RPI_WORKING_DIRECTORY}/lib/io.sh"

_help() {
  echo "-- rpi-media-centre service manager --"
  echo "Usage:"
  echo -e "\tpictl\t(backup|help|kill|logs|pause|resume|shim|start|status|stop|upgrade)\n"
}

_service_backup() {
  if [[ -e /etc/fstab ]]; then
    _configure_backup /etc/fstab "fstab"
  fi
  if [[ -d .rpi ]]; then
    _configure_backup ".rpi" "rpi-media-centre"
  fi
  if _is_service_selected "plex"; then
    _configure_backup "${RPI_PLEX_PATH_CONFIG}" "plex"
  fi
  if _is_service_selected "syncthing"; then
    _configure_backup "${RPI_SYNCTHING_PATH_CONFIG}" "syncthing"
  fi
}

_service_kill() {
  echo "Media centre now being killed ..."
  _SERVICE_REMOVE_CONTAINERS=1
  _docker_compose_command kill
  _disk_unmount_all
}

_service_logs() {
  _docker_compose_command logs -f
}

_service_pause() {
  echo "Media centre now being paused ..."
  _SERVICE_REMOVE_CONTAINERS=0
  _docker_compose_command stop
}

_service_resume() {
  if ! _is_disk_mounted_all; then
    echo "The disk is not mounted!"
    return 127
  fi

  echo "Media centre now being resumed ..."
  _docker_compose_command start
}

_service_shim() {
  echo "Installing service shim ..."
  export RPI_WORKING_DIRECTORY
  # shellcheck disable=SC2016
  envsubst '${RPI_WORKING_DIRECTORY}' < services/cli/shim.sh | sudo tee /usr/local/bin/pictl > /dev/null
  sudo chown "${USER}":"${USER}" /usr/local/bin/pictl
  sudo chmod 500 /usr/local/bin/pictl
  echo "Service shim installed!"
}

_service_start() {
  echo "Media centre now starting ..."
  _disk_mount_all
  _disk_initialize_mounts

  if _is_service_selected "samba"; then
    _configure_samba
  fi

  _docker_compose_command up -d

  if _is_service_selected "syncthing"; then
    _configure_syncthing
  fi
}

_service_status() {
  _docker_compose_command ps -a
}

_service_stop() {
  echo "Media centre now stopping ..."
  _SERVICE_REMOVE_CONTAINERS=1
  _docker_compose_command stop
  _disk_unmount_all
}

_service_upgrade() {
  echo "Media centre now being upgraded ..."
  _SERVICE_REMOVE_CONTAINERS=1
  _docker_compose_command stop
  _docker_compose_command pull
  _service_start
}

_with_configuration() {
  # $1 the command to launch
  _configure_pictl
  "${1}"
}

main() {
  local _SERVICE_REMOVE_CONTAINERS=0

  case "${1}" in
    backup)
      _with_configuration _service_backup
      ;;
    help)
      _help
      ;;
    kill)
      _with_configuration _service_kill
      ;;
    logs)
      _with_configuration _service_logs
      ;;
    pause)
      _with_configuration _service_pause
      ;;
    resume)
      _with_configuration _service_resume
      ;;
    shim)
      _with_configuration _service_shim
      ;;
    start)
      _with_configuration _service_start
      ;;
    status)
      _with_configuration _service_status
      ;;
    stop)
      _with_configuration _service_stop
      ;;
    upgrade)
      _with_configuration _service_upgrade
      ;;
    *)
      _help
      return 127
      ;;
  esac
}

main "$@"
