#!/bin/bash

set -eo pipefail

export MOUNT_POINT="/mnt/media"

_is_disk_encrypted() {
  test -f .disk
}

_is_disk_mounted() {
  mountpoint "${MOUNT_POINT}" >> /dev/null 2>&1
}

_service_disk_lock() {
  if _is_disk_encrypted; then
    if _is_disk_mounted; then
      echo "Unmounting partition ..."
      sudo umount /dev/mapper/media_centre

      echo "Sealing disk ..."
      sudo cryptsetup close /dev/mapper/media_centre
    fi
  fi
}

_service_disk_unlock() {
  if _is_disk_encrypted; then
    if ! _is_disk_mounted; then
      ENCRYPTED_DISK_UUID="$(_service_disk_uuid_read)"

      echo "Decrypting disk ..."
      sudo cryptsetup luksOpen "/dev/disk/by-uuid/${ENCRYPTED_DISK_UUID}" media_centre

      echo "Checking data ..."
      sudo fsck /dev/mapper/media_centre

      echo "Mounting partition ..."
      sudo mount /dev/mapper/media_centre "${MOUNT_POINT}" -o noatime,rw,errors=remount-ro
    fi
  fi
}

_service_disk_uuid_read() {
  tr -d "\n\r" < .disk
}

_service_docker_compose_command() {
  # $@: The command to pass to docker compose

  pushd "services" >> /dev/null

  docker compose "$@"

  if [[ "${_SERVICE_REMOVE_CONTAINERS}" == "1" ]]; then
    docker compose rm -f
  fi

  popd >> /dev/null
}

_service_help() {
  echo "-- rpi-media-centre service manager --"
  echo "Usage:"
  echo -e "\tpictl\t(help|kill|logs|pause|resume|start|status|stop|upgrade)\n"
}

_service_init_mounts() {
  mkdir -p "${MOUNT_POINT}"/plex/{config,transcode}
  mkdir -p "${MOUNT_POINT}"/samba/{cache,lib}
  mkdir -p "${MOUNT_POINT}"/shared/{media,transfer}
}

_service_prompt() {
  # 1: the prompt to display
  # 2: the variable name to save
  # 3: optionally set to "password" to suppress output

  local FLAGS="-rp"

  if [[ "${3}" == "password" ]]; then
    FLAGS="-rsp"
  fi

  while [[ -z "${!2}" ]]; do
    # shellcheck disable=SC2229,SC2162
    read "${FLAGS}" "$1" "$2"
    if [[ "${3}" == "password" ]]; then
      echo
    fi
  done
}

_service_samba_config_read() {
  if [[ -e .samba ]]; then
    {
      read -r SAMBA_USERNAME
      read -r SAMBA_PASSWORD
      read -r SAMBA_SUBNET
    } < .samba
  fi
}

_service_samba_config_write() {
  echo "${SAMBA_USERNAME}" > .samba
  echo "${SAMBA_PASSWORD}" >> .samba
  echo "${SAMBA_SUBNET}" >> .samba
  chmod 600 .samba
}

_service_server_kill() {
  echo "Media centre now being killed ..."
  _SERVICE_REMOVE_CONTAINERS=1
  _service_docker_compose_command kill
  _service_disk_lock
}

_service_server_logs() {
  _service_docker_compose_command logs -f
}

_service_server_pause() {
  echo "Media centre now being paused ..."
  _SERVICE_REMOVE_CONTAINERS=0
  _service_docker_compose_command stop
}

_service_server_resume() {
  if ! _is_disk_mounted; then
    echo "The disk is not mounted!"
    exit 127
  fi

  echo "Media centre now being resumed ..."
  _service_docker_compose_command start
}

_service_server_start() {
  echo "Media centre now starting ..."
  _service_disk_unlock
  _service_init_mounts

  _service_samba_config_read
  _service_prompt "Enter Samba Username: " "SAMBA_USERNAME"
  _service_prompt "Enter Samba Password: " "SAMBA_PASSWORD" "password"
  _service_prompt "Enter Samba Network CIDR: " "SAMBA_SUBNET"
  _service_samba_config_write

  cp -r services/data/* "${MOUNT_POINT}"/samba

  export SAMBA_USERNAME
  export SAMBA_PASSWORD
  export SAMBA_SUBNET

  _service_docker_compose_command up -d
}

_service_server_status() {
  _service_docker_compose_command ps -a
}

_service_server_stop() {
  echo "Media centre now stopping ..."
  _SERVICE_REMOVE_CONTAINERS=1
  _service_docker_compose_command stop
  _service_disk_lock
}

_service_server_upgrade() {
  echo "Media centre now being upgraded ..."
  _SERVICE_REMOVE_CONTAINERS=1
  _service_docker_compose_command stop
  _service_docker_compose_command pull

  unset SAMBA_USERNAME
  unset SAMBA_PASSWORD

  _service_server_start
}

main() {
  local _SERVICE_REMOVE_CONTAINERS=0

  case "${1}" in
    help)
      _service_help
      ;;
    kill)
      _service_server_kill
      ;;
    logs)
      _service_server_logs
      ;;
    pause)
      _service_server_pause
      ;;
    resume)
      _service_server_resume
      ;;
    start)
      _service_server_start
      ;;
    status)
      _service_server_status
      ;;
    stop)
      _service_server_stop
      ;;
    upgrade)
      _service_server_upgrade
      ;;
    *)
      _service_help
      ;;
  esac
}

main "$@"
