#!/bin/bash

set -eo pipefail

# shellcheck disable=SC2034
RPI_HOSTNAME="$(hostname)"
RPI_WORKING_DIRECTORY="$(realpath "$(dirname "$0")")"

# shellcheck source=lib/__all__.sh
source "${RPI_WORKING_DIRECTORY}/lib/__all__.sh"

_pictl_cli_kill() {
  _cli_log_warning "Media centre now being killed ..."
  _SERVICE_REMOVE_CONTAINERS=1
  _docker_compose_command kill
  _disk_manifest_unmount_all
}

_pictl_cli_logs() {
  _docker_compose_command logs -f
}

_pictl_cli_pause() {
  _cli_log_warning "Media centre now being paused ..."
  _SERVICE_REMOVE_CONTAINERS=0
  _docker_compose_command stop
}

_pictl_cli_resume() {
  _is_disk_mounted_all

  _cli_log_warning "Media centre now being resumed ..."
  _docker_compose_command start
}

_pictl_cli_start() {
  _cli_log_warning "Media centre now starting ..."
  _disk_manifest_mount_all
  _disk_initialize_mounts

  if _is_service_selected "samba"; then
    _configuration_samba
  fi

  if _is_service_selected "pihole"; then
    _configuration_pihole
  fi

  _docker_compose_command up -d

  if _is_service_selected "syncthing"; then
    _configuration_syncthing
  fi
}

_pictl_cli_status() {
  _docker_compose_command ps -a
}

_pictl_cli_stop() {
  _cli_log_warning "Media centre now stopping ..."
  _SERVICE_REMOVE_CONTAINERS=1
  _docker_compose_command stop
  _disk_manifest_unmount_all
}

_pictl_cli_upgrade() {
  _cli_log_warning "Media centre now being upgraded ..."
  _SERVICE_REMOVE_CONTAINERS=1
  _docker_compose_command stop
  _docker_compose_command pull
  _pictl_cli_start
}

_configuration_and_security() {
  _dependencies_group_cli
  _security_root_require
  _configuration_pictl
  _io_colours_load
  _security_validate

  if [[ "${1}" != "account" ]]; then
    _security_defaults_set
    _security_warning_single_user_mode
  fi
}

main() {
  local _SERVICE_REMOVE_CONTAINERS=0
  _configuration_and_security "$@"

  _cli_bootstrap

  _pictl_cli "$@"

}
main "$@"
