#!/bin/bash

set -eo pipefail

export RPI_WORKING_DIRECTORY="/rpi-media-centre"
export TEST_FORMAT="${TEST_FORMAT:-"%s"}"

# $1: a filter to match tests by

_test_runner_discover() {
  # $1: a filter to match tests by

  local __RPI_TEST_RUNNER_DISCOVERED_TEST_FILE

  while read -r -d $'\0' __RPI_TEST_RUNNER_DISCOVERED_TEST_FILE; do
    if [[ -n "${1}" ]] && [[ "${__RPI_TEST_RUNNER_DISCOVERED_TEST_FILE}" != *"${1}"* ]]; then
      continue
    fi
    __RPI_TEST_RUNNER_DISCOVERED_TEST_MODULES+=("${__RPI_TEST_RUNNER_DISCOVERED_TEST_FILE}")
  done < <(find "${RPI_WORKING_DIRECTORY}"/lib -name "test_*" -type f -print0)
}

_test_runner_execute() {
  # shellcheck disable=SC2034
  local TEST_INPUT
  # shellcheck disable=SC2034
  local TEST_OUTPUT
  # shellcheck disable=SC2034
  local TEST_RC

  set +e
  (
    # shellcheck source=/dev/null
    source /usr/local/bin/bash_unit -p "${1}" "${__RPI_TEST_RUNNER_DISCOVERED_TEST_MODULES[@]}"
  )
  __RPI_TEST_RUNNER_EXIT_CODE="$?"
  set -e
}

_test_runner_load_framework_support() {
  # shellcheck source=lib/io.sh
  source "${RPI_WORKING_DIRECTORY}/lib/io.sh"
  # shellcheck source=lib/cli/pretty/__all__.sh
  source "${RPI_WORKING_DIRECTORY}/lib/cli/pretty/__all__.sh"
  # shellcheck source=lib/testing/__all__.sh
  source "${RPI_WORKING_DIRECTORY}/lib/testing/__all__.sh"
  _mock.compile
}

_test_runner_load_project() {
  # shellcheck source=lib/__all__.sh
  source "${RPI_WORKING_DIRECTORY}/lib/__all__.sh"
  # shellcheck source=lib/__fixtures__/__all__.sh
  source "${RPI_WORKING_DIRECTORY}/lib/__fixtures__/__all__.sh"
}

_test_runner_main() {
  local __RPI_TEST_RUNNER_DISCOVERED_TEST_MODULES=()
  local __RPI_TEST_RUNNER_EXIT_CODE

  _test_runner_load_framework_support
  _test_runner_load_project

  _io_colours_escape

  __mock.persistence.registry.create
  trap __mock.persistence.registry.cleanup SIGINT

  # Allow specifying a file as the first argument
  _test_runner_discover "$1"

  shift || true

  _test_runner_execute "$@"

  __mock.persistence.registry.cleanup

  exit "${__RPI_TEST_RUNNER_EXIT_CODE}"
}

_test_runner_main "$@"
