---

services:

  plex:
    image: niallbyrne/plex-server-docker-rpi:latest
    container_name: plex
    network_mode: host
    restart: no
    volumes:
      - "${MOUNT_POINT}/plex/config:/config"
      - "${MOUNT_POINT}/plex/transcode:/transcode"
      - "${MOUNT_POINT}/shared/media:/data"

  samba:
    image: crazymax/samba:latest
    container_name: samba
    network_mode: host
    environment:
      - "BROWSABLE=yes"
      - "SAMBA_HOSTS_ALLOW=${SAMBA_SUBNET:-192.168.0.0/24}"
      - "SAMBA_USERNAME=${SAMBA_USERNAME:-nobody}"
      - "SAMBA_PASSWORD=${SAMBA_PASSWORD:-none}"
    restart: no
    volumes:
      - "${MOUNT_POINT}/samba:/data"
      - "${MOUNT_POINT}/shared/media:/samba/media"
      - "${MOUNT_POINT}/shared/transfer:/samba/transfer"
