---

services:

  plex:
    image: niallbyrne/plex-server-docker-rpi:latest
    container_name: plex
    network_mode: host
    restart: "${RPI_RESTART_POLICY}"
    volumes:
      - "${RPI_MOUNT_POINT}/plex/config:/config"
      - "${RPI_MOUNT_POINT}/plex/transcode:/transcode"
      - "${RPI_MOUNT_POINT}/shared/media:/data"

  samba:
    image: crazymax/samba:latest
    container_name: samba
    network_mode: host
    environment:
      - "BROWSABLE=yes"
      - "SAMBA_HOSTS_ALLOW=${RPI_SAMBA_SUBNET:-192.168.0.0/24}"
      - "SAMBA_USERNAME=${RPI_SAMBA_CREDENTIALS_USERNAME:-nobody}"
      - "SAMBA_PASSWORD=${RPI_SAMBA_CREDENTIALS_PASSWORD:-none}"
    restart: "${RPI_RESTART_POLICY}"
    volumes:
      - "${RPI_MOUNT_POINT}/samba:/data"
      - "${RPI_MOUNT_POINT}/shared/media:/samba/media"
      - "${RPI_MOUNT_POINT}/shared/transfer:/samba/transfer"
