---

services:

  plex:
    image: niallbyrne/plex-server-docker-rpi:latest
    container_name: plex
    network_mode: host
    profiles:
      - plex
    restart: "${RPI_RESTART_POLICY}"
    volumes:
      - "${RPI_PLEX_PATH_CONFIG}:/config"
      - "${RPI_PLEX_PATH_TRANSCODE}:/transcode"
      - "${RPI_ROOT}/shared/media:/data"

  samba:
    image: crazymax/samba:latest
    container_name: samba
    network_mode: host
    profiles:
      - samba
    environment:
      - "BROWSABLE=yes"
      - "SAMBA_HOSTS_ALLOW=${RPI_SAMBA_SUBNET:-192.168.0.0/24}"
      - "SAMBA_USERNAME=${RPI_SAMBA_CREDENTIALS_USERNAME:-nobody}"
      - "SAMBA_PASSWORD=${RPI_SAMBA_CREDENTIALS_PASSWORD:-none}"
    restart: "${RPI_RESTART_POLICY}"
    volumes:
      - "${RPI_SAMBA_PATH_CONFIG}:/data"
      - "${RPI_ROOT}/shared/media:/samba/media"
      - "${RPI_ROOT}/shared/transfer:/samba/transfer"
      - "${RPI_ROOT}/shared/syncthing:/samba/syncthing"

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: "${RPI_SYNCTHING_HOSTNAME:-syncthing}"
    environment:
      - PUID=1000
      - PGID=1000
      - STHOMEDIR=/config
    volumes:
      - "${RPI_SYNCTHING_PATH_CONFIG}:/config"
      - "${RPI_ROOT}/shared/syncthing:/var/syncthing"
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: "${RPI_RESTART_POLICY}"
    profiles:
      - syncthing
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
