#!/bin/bash

set -eo pipefail

# Global Environment Variable Defaults
export RPI_CONTAINER_GID="${RPI_CONTAINER_GID:-$(id -g)}"
export RPI_CONTAINER_UID="${RPI_CONTAINER_UID:-$(id -u)}"
export RPI_CONTAINER_UID_RO="${RPI_CONTAINER_UID_RO:-$(($(id -u) + 1))}"
export RPI_PATH_BACKUP="${RPI_PATH_BACKUP}"
export RPI_RESTART_POLICY="${RPI_RESTART_POLICY:-no}"
export RPI_ROOT="${RPI_ROOT:-/mnt/media}"

# Plex Environment Variable Defaults
export RPI_PLEX_PATH_CONFIG="${RPI_PLEX_PATH_CONFIG:-${RPI_ROOT}/plex/config}"
export RPI_PLEX_PATH_TRANSCODE="${RPI_PLEX_PATH_TRANSCODE:-${RPI_ROOT}/plex/transcode}"

# Samba Environment Variable Defaults
export RPI_SAMBA_CREDENTIALS_PASSWORD="${RPI_SAMBA_CREDENTIALS_PASSWORD}"
export RPI_SAMBA_CREDENTIALS_USERNAME="${RPI_SAMBA_CREDENTIALS_USERNAME}"
export RPI_SAMBA_HOSTNAME="${RPI_SAMBA_HOSTNAME:-${RPI_HOSTNAME}}"
export RPI_SAMBA_PATH_CONFIG="${RPI_SAMBA_PATH_CONFIG:-${RPI_ROOT}/samba}"
export RPI_SAMBA_SERVICE_DISCOVERY="${RPI_SAMBA_SERVICE_DISCOVERY:-1}"
export RPI_SAMBA_SUBNET="${RPI_SAMBA_SUBNET}"

# Syncthing Environment Variable Defaults
export RPI_SYNCTHING_CREDENTIALS_PASSWORD="${RPI_SYNCTHING_CREDENTIALS_PASSWORD}"
export RPI_SYNCTHING_CREDENTIALS_USERNAME"${RPI_SYNCTHING_CREDENTIALS_USERNAME}"
export RPI_SYNCTHING_PATH_CONFIG="${RPI_SYNCTHING_PATH_CONFIG:-${RPI_ROOT}/syncthing}"

# Service Selection Defaults
RPI_SERVICES=("${RPI_SERVICES[@]:-plex}" "${RPI_SERVICES[@]:-samba}")
