#!/bin/bash

set -eo pipefail

# Global Environment Variable Defaults
export RPI_CONTAINER_GID="${RPI_CONTAINER_GID:-$(id -g)}"
export RPI_CONTAINER_UID="${RPI_CONTAINER_UID:-$(id -u)}"
export RPI_CONTAINER_UID_RO="${RPI_CONTAINER_UID_RO:-$(($(id -u) + 1))}"
export RPI_CONTAINER_USERNAME
export RPI_EXECUTION_DIRECTORY="${RPI_EXECUTION_DIRECTORY:-"${PWD}"}"
export RPI_MANIFEST_EDITOR="${RPI_MANIFEST_EDITOR:-"/usr/bin/vi"}"
export RPI_PATH_BACKUP="${RPI_PATH_BACKUP}"
export RPI_RESTART_POLICY="${RPI_RESTART_POLICY:-no}"
export RPI_ROOT="${RPI_ROOT:-/mnt/media}"

RPI_CONTAINER_USERNAME="$(id -un "${RPI_CONTAINER_UID}")"

# Backup Environment Variable Defaults
export RPI_BACKUP_PATH_QUEUE_ROOT="${RPI_BACKUP_PATH_QUEUE_ROOT:-"${RPI_WORKING_DIRECTORY}/.backups"}"
export RPI_BACKUP_SCHEDULER_START_TIME="${RPI_BACKUP_SCHEDULER_START_TIME:-"00:00:00"}"
export RPI_BACKUP_SCHEDULER_END_TIME="${RPI_BACKUP_SCHEDULER_END_TIME:-"06:00:00"}"
export RPI_BACKUP_SCHEDULING_HOUR="${RPI_BACKUP_SCHEDULING_HOUR:-"12"}"

# Plex Environment Variable Defaults
export RPI_PLEX_PATH_CONFIG="${RPI_PLEX_PATH_CONFIG:-${RPI_ROOT}/plex/config}"
export RPI_PLEX_PATH_TRANSCODE="${RPI_PLEX_PATH_TRANSCODE:-${RPI_ROOT}/plex/transcode}"

# Samba Environment Variable Defaults
export RPI_SAMBA_CREDENTIALS_PASSWORD="${RPI_SAMBA_CREDENTIALS_PASSWORD}"
export RPI_SAMBA_CREDENTIALS_USERNAME="${RPI_SAMBA_CREDENTIALS_USERNAME}"
export RPI_SAMBA_HOSTNAME="${RPI_SAMBA_HOSTNAME:-${RPI_HOSTNAME}}"
export RPI_SAMBA_PATH_CONFIG="${RPI_SAMBA_PATH_CONFIG:-${RPI_ROOT}/samba}"
export RPI_SAMBA_SERVICE_DISCOVERY="${RPI_SAMBA_SERVICE_DISCOVERY:-1}"
export RPI_SAMBA_SUBNET="${RPI_SAMBA_SUBNET}"
export RPI_SAMBA_WORKGROUP="${RPI_SAMBA_WORKGROUP:-"WORKGROUP"}"

# Syncthing Environment Variable Defaults
export RPI_SYNCTHING_CREDENTIALS_PASSWORD="${RPI_SYNCTHING_CREDENTIALS_PASSWORD}"
export RPI_SYNCTHING_CREDENTIALS_USERNAME"${RPI_SYNCTHING_CREDENTIALS_USERNAME}"
export RPI_SYNCTHING_PATH_CONFIG="${RPI_SYNCTHING_PATH_CONFIG:-${RPI_ROOT}/syncthing}"

# Service Selection Defaults
RPI_SERVICES=("${RPI_SERVICES[@]:-plex}" "${RPI_SERVICES[@]:-samba}")
