#!/bin/bash

set -eo pipefail

# Global Environment Variable Defaults

RPI_COLOUR_BOOLEAN="${RPI_COLOUR_BOOLEAN:-"0"}"
# shellcheck disable=SC2034
RPI_PROJECT_REPOSITORY="https://github.com/niall-byrne/rpi-media-centre"
# shellcheck disable=SC2034
RPI_CLI_JUST_COMPILED_BOOLEAN="0"

export RPI_CLI_MEMORY_ONLY_BOOLEAN="${1:-"0"}"
export RPI_EXECUTION_DIRECTORY="${RPI_EXECUTION_DIRECTORY:-"${PWD}"}"
export RPI_HOST_IP="${RPI_HOST_IP:-"$(hostname -I | cut -f 1 -d ' ' || "127.0.0.1")"}"
export RPI_HOST_TZ="${RPI_HOST_TZ:-"$(cat /etc/timezone || "UTC")"}"
export RPI_MANIFEST_EDITOR="${RPI_MANIFEST_EDITOR:-"/usr/bin/vi"}"
export RPI_PATH_BACKUP="${RPI_PATH_BACKUP}"
export RPI_RESTART_POLICY="${RPI_RESTART_POLICY:-no}"
export RPI_ROOT="${RPI_ROOT:-/mnt/media}"

export RPI_SVC_GROUPNAME="${RPI_SVC_GROUPNAME:-""}"
export RPI_SVC_USERNAME="${RPI_SVC_USERNAME:-""}"
export RPI_SVC_GID=${RPI_SVC_GID:-""}
export RPI_SVC_UID=${RPI_SVC_UID:-""}
export RPI_SVC_UID_RO=${RPI_SVC_UID_RO:-""}

# Backup Environment Variable Defaults
export RPI_BACKUP_PATH_QUEUE_ROOT="${RPI_BACKUP_PATH_QUEUE_ROOT:-"/var/local/rpi/backup_jobs"}"
export RPI_BACKUP_SCHEDULER_START_TIME="${RPI_BACKUP_SCHEDULER_START_TIME:-"00:00:00"}"
export RPI_BACKUP_SCHEDULER_END_TIME="${RPI_BACKUP_SCHEDULER_END_TIME:-"06:00:00"}"
export RPI_BACKUP_SCHEDULING_HOUR="${RPI_BACKUP_SCHEDULING_HOUR:-"12"}"

# Pihole Environment Variable Defaults
export RPI_PIHOLE_CREDENTIALS_PASSWORD="${RPI_PIHOLE_CREDENTIALS_PASSWORD}"
export RPI_PIHOLE_PATH_CONFIG="${RPI_PIHOLE_PATH_CONFIG:-"/var/local/rpi/pihole/config"}"
export RPI_PIHOLE_PATH_DNSMASQ="${RPI_PIHOLE_PATH_DNSMASQ:-"/var/local/rpi/pihole/dnsmasq"}"

# Plex Environment Variable Defaults
export RPI_PLEX_PATH_CONFIG="${RPI_PLEX_PATH_CONFIG:-"/var/local/rpi/plex/config"}"
export RPI_PLEX_PATH_TRANSCODE="${RPI_PLEX_PATH_TRANSCODE:-${RPI_ROOT}/plex/transcode}"

export RPI_PLEX_PATH_DATA_MOUNT_1="${RPI_PLEX_PATH_DATA_MOUNT_1:-"${RPI_ROOT}/shared/media:/data"}"
export RPI_PLEX_PATH_DATA_MOUNT_2="${RPI_PLEX_PATH_DATA_MOUNT_2:-/dev/null:/null}"
export RPI_PLEX_PATH_DATA_MOUNT_3="${RPI_PLEX_PATH_DATA_MOUNT_3:-/dev/null:/null}"
export RPI_PLEX_PATH_DATA_MOUNT_4="${RPI_PLEX_PATH_DATA_MOUNT_4:-/dev/null:/null}"
export RPI_PLEX_PATH_DATA_MOUNT_5="${RPI_PLEX_PATH_DATA_MOUNT_5:-/dev/null:/null}"
export RPI_PLEX_PATH_DATA_MOUNT_6="${RPI_PLEX_PATH_DATA_MOUNT_6:-/dev/null:/null}"
export RPI_PLEX_PATH_DATA_MOUNT_7="${RPI_PLEX_PATH_DATA_MOUNT_7:-/dev/null:/null}"
export RPI_PLEX_PATH_DATA_MOUNT_8="${RPI_PLEX_PATH_DATA_MOUNT_8:-/dev/null:/null}"
export RPI_PLEX_PATH_DATA_MOUNT_9="${RPI_PLEX_PATH_DATA_MOUNT_9:-/dev/null:/null}"

# Samba Environment Variable Defaults
export RPI_SAMBA_CREDENTIALS_PASSWORD="${RPI_SAMBA_CREDENTIALS_PASSWORD}"
export RPI_SAMBA_CREDENTIALS_USERNAME="${RPI_SAMBA_CREDENTIALS_USERNAME}"
export RPI_SAMBA_HOSTNAME="${RPI_SAMBA_HOSTNAME:-${RPI_HOSTNAME}}"
export RPI_SAMBA_PATH_CONFIG="${RPI_SAMBA_PATH_CONFIG:-"/var/local/samba/config"}"
export RPI_SAMBA_SERVICE_DISCOVERY="${RPI_SAMBA_SERVICE_DISCOVERY:-1}"
export RPI_SAMBA_SUBNET="${RPI_SAMBA_SUBNET}"
export RPI_SAMBA_WORKGROUP="${RPI_SAMBA_WORKGROUP:-"WORKGROUP"}"

export RPI_SAMBA_PATH_DATA_MOUNT_1="${RPI_ROOT}/shared/media:/samba/media"
export RPI_SAMBA_PATH_DATA_MOUNT_2="${RPI_ROOT}/shared/transfer:/samba/transfer"
export RPI_SAMBA_PATH_DATA_MOUNT_3="${RPI_ROOT}/shared/syncthing:/samba/syncthing"
export RPI_SAMBA_PATH_DATA_MOUNT_4="${RPI_SAMBA_PATH_DATA_MOUNT_4:-/dev/null:/null}"
export RPI_SAMBA_PATH_DATA_MOUNT_5="${RPI_SAMBA_PATH_DATA_MOUNT_5:-/dev/null:/null}"
export RPI_SAMBA_PATH_DATA_MOUNT_6="${RPI_SAMBA_PATH_DATA_MOUNT_6:-/dev/null:/null}"
export RPI_SAMBA_PATH_DATA_MOUNT_7="${RPI_SAMBA_PATH_DATA_MOUNT_7:-/dev/null:/null}"
export RPI_SAMBA_PATH_DATA_MOUNT_8="${RPI_SAMBA_PATH_DATA_MOUNT_8:-/dev/null:/null}"
export RPI_SAMBA_PATH_DATA_MOUNT_9="${RPI_SAMBA_PATH_DATA_MOUNT_9:-/dev/null:/null}"

# Syncthing Environment Variable Defaults
export RPI_SYNCTHING_CREDENTIALS_PASSWORD="${RPI_SYNCTHING_CREDENTIALS_PASSWORD}"
export RPI_SYNCTHING_CREDENTIALS_USERNAME"${RPI_SYNCTHING_CREDENTIALS_USERNAME}"
export RPI_SYNCTHING_PATH_CONFIG="${RPI_SYNCTHING_PATH_CONFIG:-"/var/local/syncthing/config"}"

export RPI_SYNCTHING_PATH_DATA_MOUNT_1="${RPI_ROOT}/shared/syncthing:/var/syncthing"
export RPI_SYNCTHING_PATH_DATA_MOUNT_2="${RPI_SYNCTHING_PATH_CUSTOM_MOUNT_2:-/dev/null:/null}"
export RPI_SYNCTHING_PATH_DATA_MOUNT_3="${RPI_SYNCTHING_PATH_CUSTOM_MOUNT_3:-/dev/null:/null}"
export RPI_SYNCTHING_PATH_DATA_MOUNT_4="${RPI_SYNCTHING_PATH_CUSTOM_MOUNT_4:-/dev/null:/null}"
export RPI_SYNCTHING_PATH_DATA_MOUNT_5="${RPI_SYNCTHING_PATH_CUSTOM_MOUNT_5:-/dev/null:/null}"
export RPI_SYNCTHING_PATH_DATA_MOUNT_6="${RPI_SYNCTHING_PATH_CUSTOM_MOUNT_2:-/dev/null:/null}"
export RPI_SYNCTHING_PATH_DATA_MOUNT_7="${RPI_SYNCTHING_PATH_CUSTOM_MOUNT_3:-/dev/null:/null}"
export RPI_SYNCTHING_PATH_DATA_MOUNT_8="${RPI_SYNCTHING_PATH_CUSTOM_MOUNT_4:-/dev/null:/null}"
export RPI_SYNCTHING_PATH_DATA_MOUNT_9="${RPI_SYNCTHING_PATH_CUSTOM_MOUNT_5:-/dev/null:/null}"

# Service Selection Defaults
RPI_SERVICES=("${RPI_SERVICES[@]:-plex}" "${RPI_SERVICES[@]:-samba}")
