#!/bin/bash
# shellcheck disable=SC2034

# pictl settings cli library

set -eo pipefail

RPI_EVENTS_PATH="/etc/rpi/events"

RPI_MANIFEST_BACKUP="/etc/rpi/backup"
RPI_MANIFEST_CONFIG="/etc/rpi/config"
RPI_MANIFEST_CRYPT="/etc/rpi/crypt"

# KCOV_EXCLUDE_BEGIN
RPI_THEME_COMPONENTS=(
  THEME_DETAIL
  THEME_ENTITY
  THEME_HEADER
  THEME_HIGHLIGHT
  THEME_INFO
  THEME_QUOTES
  THEME_TITLE
  THEME_BRACKETS_STYLE_1
  THEME_BRACKETS_STYLE_1_INNER
  THEME_BRACKETS_STYLE_2
  THEME_BRACKETS_STYLE_2_INNER
  THEME_DEVICE
  THEME_DEVICE_CONNECTORS
  THEME_DISK_GAUGE_SPACE_CRITICAL
  THEME_DISK_GAUGE_SPACE_WARNING
  THEME_DISK_GAUGE_SPACE_OK
  THEME_DISK_INDICATOR_SPACE_FREE
  THEME_DISK_INDICATOR_ACTIVE
  THEME_DISK_INDICATOR_IDLE
)
# KCOV_EXCLUDE_BEGIN

# KCOV_EXCLUDE_BEGIN
RPI_LOGGER_THEME_COMPONENTS=(
  THEME_LOGGER_ERROR
  THEME_LOGGER_WARNING
  THEME_LOGGER_INFO
  THEME_LOGGER_NOTICE
  THEME_LOGGER_SUCCESS
)
# KCOV_EXCLUDE_END
