---

global:
  - "create mask = 0640"
  - "force create mode = 0640"
  - "directory mask = 0750"
  - "force directory mode = 0750"
  - "fruit:resource = file"
  - "fruit:nfs_aces = no"

auth:
  - user: "${SAMBA_USERNAME}"
    group: "media"
    uid: "1000"
    gid: "1000"
    password: "${SAMBA_PASSWORD}"

  - user: "android"
    group: "media"
    uid: "1001"
    gid: "1000"
    password: "${SAMBA_PASSWORD}"

share:
  - name: "media"
    path: "/samba/media"
    browsable: "${BROWSABLE-no}"
    readonly: "no"
    guestok: "no"
    validusers: "${SAMBA_USERNAME},android"
    writelist: "${SAMBA_USERNAME}"

  - name: "transfer"
    path: "/samba/transfer"
    browsable: "${BROWSABLE-no}"
    readonly: "no"
    guestok: "no"
    validusers: "${SAMBA_USERNAME}"
    writelist: "${SAMBA_USERNAME}"

  - name: "syncthing"
    path: "/samba/syncthing"
    browsable: "${BROWSABLE-no}"
    readonly: "no"
    guestok: "no"
    validusers: "${SAMBA_USERNAME}"
    writelist: "${SAMBA_USERNAME}"
