#!/bin/bash

# Automatically generated by pictl on Mon Sep 15 19:53:34 UTC 2025

_test_cli_usage() {
  echo -e "${THEME_TITLE}-- pictl cli generator scenario 1 --${THEME_NC}"
  echo -e "${THEME_HEADER}Usage:${THEME_NC}"
  echo -e "  ${THEME_HIGHLIGHT}test ${THEME_BRACKETS_STYLE_2}[${THEME_BRACKETS_STYLE_2_INNER}SUBCOMMAND${THEME_BRACKETS_STYLE_2}]${THEME_NC}${THEME_NC}"
  echo -e "    ${THEME_ENTITY}command1                                  ${THEME_NC} - run the default command1 function"
  echo -e "    ${THEME_ENTITY}command2                                  ${THEME_NC} - run a custom command2 function"
  echo -e "    ${THEME_ENTITY}command3 ${THEME_BRACKETS_STYLE_2}[${THEME_BRACKETS_STYLE_2_INNER}SUBCOMMAND${THEME_BRACKETS_STYLE_2}]${THEME_NC}                     ${THEME_NC} - run a custom command3 function that has subcommands"
  echo -e "    ${THEME_ENTITY}command4                                  ${THEME_NC} - run the default command4 function with a setup command"
  echo -e "    ${THEME_ENTITY}command5                                  ${THEME_NC} - run a custom command5 function with a setup command"
}

_test_cli_usage_error() {
  {
    _test_cli_usage
  } >&2
  return 127
}

_test_cli() {
  case "${1}" in
    command1)
      shift
      _test_cli_command1 "$@"
      ;;
    command2)
      shift
      custom2_function "$@"
      ;;
    command3)
      shift
      custom3_cli "$@"
      ;;
    command4)
      shift
      setup_command_4 "$@" || return "$?"
      _test_cli_command4 "$@"
      ;;
    command5)
      shift
      setup_command_5 "$@" || return "$?"
      custom5_function "$@"
      ;;
    help)
      _test_cli_usage
      ;;
    *)
      _test_cli_usage
      return 127
      ;;
  esac
}

_command3_cli_usage() {
  echo -e "${THEME_TITLE}-- pictl cli generator scenario 1 command3 --${THEME_NC}"
  echo -e "${THEME_HEADER}Usage:${THEME_NC}"
  echo -e "  ${THEME_HIGHLIGHT}test command3 ${THEME_BRACKETS_STYLE_2}[${THEME_BRACKETS_STYLE_2_INNER}SUBCOMMAND${THEME_BRACKETS_STYLE_2}]${THEME_NC}${THEME_NC}"
  echo -e "    ${THEME_ENTITY}subcommand1 ${THEME_BRACKETS_STYLE_2}(${THEME_BRACKETS_STYLE_2_INNER}FILENAME${THEME_BRACKETS_STYLE_2})${THEME_NC}                    ${THEME_NC} - run the default subcommand1 function"
  echo -e "    ${THEME_ENTITY}subcommand2 ${THEME_BRACKETS_STYLE_2}[${THEME_BRACKETS_STYLE_2_INNER}SUBCOMMAND${THEME_BRACKETS_STYLE_2}]${THEME_NC}                  ${THEME_NC} - run the custom subcommand2 function with a setup command"
  echo -e "    ${THEME_ENTITY}subcommand3 ${THEME_BRACKETS_STYLE_2}[${THEME_BRACKETS_STYLE_2_INNER}ARG${THEME_BRACKETS_STYLE_2}]${THEME_NC}                         ${THEME_NC} - run the custom subcommand3 function with arguments"
}

_command3_cli_usage_error() {
  {
    _command3_cli_usage
  } >&2
  return 127
}

_command3_cli() {
  case "${1}" in
    subcommand1)
      shift
      command3_before_all_setup_command "$@" || return "$?"
      _command3_cli_subcommand1 "$@"
      ;;
    subcommand2)
      shift
      command3_before_all_setup_command "$@" || return "$?"
      setup_subcommand3 "$@" || return "$?"
      subcommand2_cli "$@"
      ;;
    subcommand3)
      shift
      command3_before_all_setup_command "$@" || return "$?"
      subcommand3_function arg1 arg2 arg3 "$@"
      ;;
    help)
      _command3_cli_usage
      ;;
    *)
      _command3_cli_usage
      return 127
      ;;
  esac
}
