#!/bin/bash

# Automatically generated by pictl on Mon Sep 15 19:53:34 UTC 2025

_test_with_switches_cli_usage() {
  echo -e "${THEME_TITLE}-- test_with_switches cli generator scenario 2 --${THEME_NC}"
  echo -e "${THEME_HEADER}Usage:${THEME_NC}"
  echo -e "  ${THEME_HIGHLIGHT}test ${THEME_BRACKETS_STYLE_2}(${THEME_BRACKETS_STYLE_2_INNER}OPTIONS${THEME_BRACKETS_STYLE_2})${THEME_NC}${THEME_NC}"
  echo -e "   ${THEME_ENTITY}-a${THEME_NC} ${THEME_BRACKETS_STYLE_1}[${THEME_BRACKETS_STYLE_1_INNER}EXAMPLE_SWITCH_1${THEME_BRACKETS_STYLE_1}]${THEME_NC}"
  echo -e "   ${THEME_ENTITY}-b${THEME_NC} ${THEME_BRACKETS_STYLE_1}[${THEME_BRACKETS_STYLE_1_INNER}<optional> EXAMPLE_SWITCH_2${THEME_BRACKETS_STYLE_1}]${THEME_NC}"
}

_test_with_switches_cli_usage_error() {
  {
    _test_with_switches_cli_usage
  } >&2
  return 127
}

_test_with_switches_cli() {
  case "${1}" in
    option1)
      shift
      _test_with_switches_cli_option1 "$@"
      ;;
    option2)
      shift
      _test_with_switches_cli_option2 "$@"
      ;;
    option3)
      shift
      _test_with_switches_cli_option3 "$@"
      ;;
    help)
      _test_with_switches_cli_usage
      ;;
    *)
      _test_with_switches_cli_usage
      return 127
      ;;
  esac
}
